name: EASE

model:
  reg_weight: 250

saved_model: False
saved_model_name: model_0

recbole_params:
  USER_ID_FIELD: 'user_id'
  ITEM_ID_FIELD: 'item_id'
  RATING_FIELD: 'rating'
  TIME_FIELD: 'timestamp'
  benchmark_filename: ['train', 'test', 'test']
  load_col: {'inter': ['user_id', 'item_id', 'rating']}

  gpu_id: 0
  train_batch_size: 4096
  eval_batch_size: 4096000

  neg_sampling: None
  show_progress: True

enable_optimization: False
optuna_optimizer:
  n_trials: 40
  k_optimization: [10]
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 42
  pruner:
    _target_: optuna.pruners.MedianPruner
  hyperparameters_vary:
    float:
      - name: reg_weight
        low: 1.0
        high: 1000.0
        log: True