defaults:
  - dataset: foursquare
  - library: implicit
  - _self_
results_folder: results

default_dataset_parameters:
  min_user_rating: 5
  min_item_rating: 5
  splitting:
    strategy: temporal
    train_size: .8
    val_size: .1
    test_size: .1