data: results/metrics
methods:
 - implicit:
   - als
   - bpr
 - lightfm
metric: Recall@K


# methods
# all - all found methods
# list:
# - lightfm
# - als
# - bpr
# metric:
# ['Precision@k', 'Recall@K', 'MAP@K', 'nDCG@k', 'MRR@k', 'HitRate@k', 'Coverage@K', 'Time_fit', 'Time_predict'] - choose one of it
