name: bpr

model:
  factors: 80
  regularization: 90
  learning_rate: 0.001
  iterations: 65

learning:
  show_progress: True

saved_model: False
saved_model_name: model_0

enable_optimization: True
optuna_optimizer:
  n_trials: 40
  k_optimization: [10]
  sampler:
    _target_: optuna.samplers.TPESampler
    seed: 42
  pruner:
    _target_: optuna.pruners.MedianPruner
  hyperparameters_vary:
    int:
      - name: factors
        low: 50
        high: 200
        step: 5
      - name: iterations
        low: 10
        high: 100
        step: 5
    float:
      - name: 'regularization'
        low: .0001
        high: 10
        log: True
      - name: learning_rate
        low: 0.001
        high: 0.1
        log: False 