name: data_smm
data_src: data/data_smm
ratings_file: interactions_small.parquet
user_column: user_id
item_column: item_id
rating_column: weight
date_column: datetime
min_item_ratings: 50
min_user_ratings: 50
weighted: True
positive_threshold: 0
meta_user: False
meta_item: False
splitting:
  strategy: ${default_dataset_parameters.splitting.strategy}
  train_size: ${default_dataset_parameters.splitting.train_size}
  val_size: ${default_dataset_parameters.splitting.val_size}
  test_size: ${default_dataset_parameters.splitting.test_size}