name: gowalla
data_src: data/gowalla
ratings_file: interactions.parquet
user_column: userId
item_column: locationId
rating_column: relevant
date_column: checkInTime
min_item_ratings: ${default_dataset_parameters.min_item_rating}
min_user_ratings: ${default_dataset_parameters.min_user_rating}
weighted: False
positive_threshold: 0
meta_user: False
meta_item: False
splitting:
  strategy: ${default_dataset_parameters.splitting.strategy}
  train_size: ${default_dataset_parameters.splitting.train_size}
  val_size: ${default_dataset_parameters.splitting.val_size}
  test_size: ${default_dataset_parameters.splitting.test_size}