name: mts_library
data_src: data/mts_library
ratings_file: ratings.parquet
user_column: user_id
item_column: item_id
rating_column: interactions
date_column: start_date
min_item_ratings: ${default_dataset_parameters.min_item_rating}
min_user_ratings: ${default_dataset_parameters.min_user_rating}
weighted: True
positive_threshold: .3
meta_user: False
meta_item: False
splitting:
  strategy: ${default_dataset_parameters.splitting.strategy}
  train_size: ${default_dataset_parameters.splitting.train_size}
  val_size: ${default_dataset_parameters.splitting.val_size}
  test_size: ${default_dataset_parameters.splitting.test_size}