name: rekko
data_src: data/rekko
ratings_file: ratings.parquet
nip_file: ratings.parquet
user_column: user_uid
item_column: element_uid
rating_column: rating
date_column: ts
min_item_ratings: ${default_dataset_parameters.min_item_rating}
min_user_ratings: ${default_dataset_parameters.min_user_rating}
weighted: True
positive_threshold: 7
meta_user: False
meta_item: False
splitting:
  strategy: ${default_dataset_parameters.splitting.strategy}
  train_size: ${default_dataset_parameters.splitting.train_size}
  val_size: ${default_dataset_parameters.splitting.val_size}
  test_size: ${default_dataset_parameters.splitting.test_size}
